In [22]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

def stepFunction(t):
    if t >= 0:
        return 1
    return 0

def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [37]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    for i in range(len(y)):
        y_hat = prediction(X[i],W,b)

        # y[i] is the label
        # y_hat is the prediction classification
        if (y[i] == 1) & (y_hat==0):
            # If the point is classified negative,
            # but it has a positive label, add

            W[0] = W[0] + X[i][0]*learn_rate
            W[1] = W[1] + X[i][1]*learn_rate
            b = b + learn_rate
        elif (y[i] == 0) & (y_hat==1):
            # If the point is classified positive,
            # but it has a negative label, subtract
            W[0] = W[0] - X[i][0]*learn_rate
            W[1] = W[1] - X[i][1]*learn_rate
            b = b - learn_rate

    return W, b

In [40]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(1):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [41]:
import pandas as pd

df = pd.read_csv('data.csv', header=None)
X = df.iloc[:,0:2].values
y = df.iloc[:,2].values
trainPerceptronAlgorithm(X,y)

[(array([-0.9061699]), array([-2.39017645])),
 (array([-0.93839023]), array([-1.91280364])),
 (array([-0.95413858]), array([-1.67947772])),
 (array([-0.96347492]), array([-1.54115151])),
 (array([-0.9696529]), array([-1.44961925])),
 (array([-0.97404331]), array([-1.38457149])),
 (array([-0.97732392]), array([-1.33596624])),
 (array([-0.97986833]), array([-1.29826865])),
 (array([-0.98189934]), array([-1.2681774])),
 (array([-0.9835581]), array([-1.24360134])),
 (array([-0.98493837]), array([-1.2231515])),
 (array([-0.98610484]), array([-1.2058692])),
 (array([-0.98710362]), array([-1.19107139])),
 (array([-0.98796844]), array([-1.17825825])),
 (array([-0.98872457]), array([-1.16705559])),
 (array([-0.98939127]), array([-1.15717774])),
 (array([-0.98998354]), array([-1.14840281])),
 (array([-0.99051317]), array([-1.14055585])),
 (array([-0.9909896]), array([-1.13349705])),
 (array([-0.99142047]), array([-1.12711334])),
 (array([-0.99181201]), array([-1.12131229])),
 (array([-0.99216938